name: Hexo Deployment
# Thanks ltfjx

on:
  push:
    branches: [main]

jobs:
  hexo-deployment:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.15.1'

    - name: Install dependencies & Generate static files
      run: |
        npm install --location=global hexo-cli
        npm install
        hexo clean
        hexo generate
      
    - name: Deploy to Cloudflare Pages
      env:
        GIT_NAME: FA
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/lingrottin/FarawayAsh.git
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global init.defaultBranch cf_web
        cd ./public && git init && git add -A
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force "https://$GH_TOKEN@$REPO" cf_web:cf_web
        
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIV_KEY }}
        ARGS: '-avz -u --chown=www:www'
        SOURCE: "public/"
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_PORT: ${{ secrets.SERVER_PORT }}
        REMOTE_USER: ${{ secrets.SERVER_USER }}
        TARGET: '/www/wwwroot/enita.cn/'
