name: Hexo Deployment
# Thanks ltfjx

on:
  push:
    branches: [main]

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.15.1'

    - name: Install dependencies & Generate static files
      run: |
        npm install --location=global hexo-cli
        npm install
        hexo clean
        hexo generate
      
    - name: Deploy to Cloudflare Pages
      env:
        GIT_NAME: FA
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/lingrottin/FarawayAsh
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global init.defaultBranch cf_web
        cd ./public && git init && git add -A
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO"
        
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIV_KEY }}
        ARGS: '-avz --delete --chown=nginx:nginx --rsync-path="sudo rsync"'
        SOURCE: "public/"
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: 'uofadmin'
        TARGET: '/usr/local/openresty/nginx/fa/'
